### ISSUE TITLE
Add algorithm in language of your choice

### ISSUE THREAD

**Issue by kvaluruk** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#1]
**Contributing Guidelines**
- The repository is structured language-wise i.e. algorithms in a certain language go in a specific folder.
- The naming convention to be followed is `algo_name.language_extention` i.e. the overall path should be `language/algo_name.language_extention`
- It is your choice to include only the function or the entire program for the algorithm.
- If the folder for your language does not exist, create a new one.
- Don't be afraid to make a PR!

**How to make PR**
1. Fork Repo on Web Page
2. Make your changes on your forked repo
3. Make Pull Request to master

**Comment by Anshumank399** [comment]
Please Review my PR #44

**Comment by itsVagabond** [comment]
#46 Added Knapsack Problem. Please review

**Comment by Anshumank399** [comment]
Please Review my PR #69

**Comment by Anshumank399** [comment]
Please Review my PR #77

**Comment by wikiabhi** [comment]
added gcd algo in cpp #198

**Comment by kr-nkit** [comment]
Added factorial Java code #202

**Comment by wikiabhi** [comment]
added fibonacci code using dynamic programming in cpp #203 Please merge the PR.

**Comment by PritishSehzpaul** [comment]
Hi please review the PR #687 **(Loop Detection in Linked List)** and merge. Thanks!

**Comment by anshulkhattar** [comment]
added quiz in java using data structures via #701

**Comment by shivank1404** [comment]
Please view my PR. Added Longest common substrings codes

**Comment by phenomenal45** [comment]
hello i want to contribute in this
