### ISSUE TITLE
Sort existing codes into either algorithms or data structures

### ISSUE THREAD

**Issue by goelchahat** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#185]
Currently the files are in the form `language/filename`. 
Change this to `language/algorithms/filename` for algorithms or `language/ds/filename` for data structures.

[Edit] Limit your changes to one or two languages.

**Comment by wikiabhi** [comment]
i am working on it.

**Comment by kvaluruk** [comment]
@wikiabhi Please work on any one language, and not all.

**Comment by wikiabhi** [comment]
okay, i am working on cpp

**Comment by Teodor1998** [comment]
I'll take Java then.

**Comment by kvaluruk** [comment]
@wikiabhi @Teodor1998 please go ahead! Thanks!

**Comment by wikiabhi** [comment]
done #189

**Comment by ShailyTyagi** [comment]
I am working on c

**Comment by wikiabhi** [comment]
working on python now.

**Comment by kr-nkit** [comment]
working on JavaScript

**Comment by ronika-das** [comment]
working on csharp and go

**Comment by kr-nkit** [comment]
Done JavaSCript #193

**Comment by ronika-das** [comment]
Done #194

**Comment by ShailyTyagi** [comment]
Done #195

**Comment by wikiabhi** [comment]
Python done #196

**Comment by kr-nkit** [comment]
Working on PHP codes

**Comment by kr-nkit** [comment]
Done PHP #197

**Comment by kr-nkit** [comment]
organised dart codes #205

**Comment by kr-nkit** [comment]
organised kotlin codes #207

**Comment by MohabMohamed** [comment]
working on ruby
