### ISSUE TITLE
Add data structure in language of your choice

### ISSUE THREAD

**Issue by kvaluruk** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#21]
**Contributing Guidelines**
- The repository is structured language-wise i.e. data structures in a certain language go in a specific folder.
- The naming convention to be followed is ds_name.language_extention i.e. the overall path should be language/ds_name.language_extention
- It is your choice to include only the function or the entire program for the algorithm.
- If the folder for your language does not exist, create a new one.
- Don't be afraid to make a PR!

**How to make PR**
1. Fork Repo on Web Page
2. Make your changes to your forked repo
3. Make Pull Request to master

**Comment by Vaibzz** [comment]
please merge my PR #34

**Comment by Vaibzz** [comment]
please merge my PR #52

**Comment by CoderJolly** [comment]
pls review PR#59

**Comment by Vaibzz** [comment]
please merge my PR #64

**Comment by adi44** [comment]
I would like to work on this issue

**Comment by kvaluruk** [comment]
@adi44 please go ahead

**Comment by amarjeet045** [comment]
hello,i want to contribute in this issue.is this open for me ? please guide me.

**Comment by AdityaShD** [comment]
please review  #263

**Comment by amarjeet045** [comment]
I can't understand what I have to do, please suggest me or I should add a file in data structure folder with the data structure

**Comment by koderproxy** [comment]
want to work on this issue

**Comment by rbo13** [comment]
Want to work on this one also :)

**Comment by m-zawilski** [comment]
Improved JS LinkedList: #688 
I would like to work on other data structures in JS as well (Binomial Heap, Black-Red Tree)

**Comment by DavidSotoA** [comment]
Hi, I create a Tree structure for haskell and some functions like createTree, insertNode, inOrder, preOrder and postOrder in #832. Please review it.

**Comment by Vtayal** [comment]
working on a data structure :)

**Comment by jankit311** [comment]
please merge my PR #954

**Comment by rbo13** [comment]
Also, please merge my PR on: https://github.com/kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18/pull/582 if no one is implementing it 👍
