### ISSUE TITLE
Segregation in each language

### ISSUE THREAD

**Issue by dhairyakhale** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#28]
We can create sub-folders in each language. It will make this task less confusing.
For starters, we can separate the codes into 'algorithms' and 'data structures'.

**Comment by kvaluruk** [comment]
This **should** be implemented ideally.
If anyone is willing to work on dividing the existing codes, they are most welcome to seperate the code into sub-folders. 
However, I think that it shouldn't be compulsory for newcomers to seperate the code they are adding.

**Comment by cheevu-RS** [comment]
Working on javascript
