### ISSUE TITLE
Add searching algorithms

### ISSUE THREAD

**Issue by goelchahat** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#285]
## Contributing Guidelines
- The repository is structured language-wise i.e. algorithms in a certain language go in a specific folder.
- The naming convention to be followed is `algo_name.language_extention` i.e. the overall path should be `language/algo_name.language_extention`
- It is your choice to include only the function or the entire program for the algorithm.
- If the folder for your language does not exist, create a new one.
- Don't be afraid to make a PR!

## How to make PR
- Fork Repo on Web Page
- Make your changes on your forked repo
- Make Pull Request to master

**Comment by srsandy** [comment]
Can i take it for java ?

**Comment by aavizek** [comment]
@goelchahat may i add heapsort algorithm in cpp?

**Comment by amrithm98** [comment]
Can I take it for C++ ? I can implement search algorithms with neat code n doc

**Comment by shubhamshee** [comment]
can i take it for java?

**Comment by Haadia** [comment]
Can I take it for python ?

**Comment by rbo13** [comment]
I will create a PR for Golang :)

**Comment by amohata007** [comment]
https://github.com/amohata007/Hacktoberfest
contribute here....it is totally awesome and very easy to contribute.
@goelchahat @Artistic18 @srsandy @amrithm98 @shubhamshee @zara-nicole @hazel1898 @faouziamrouche @Vaibzz @Electrux @eLobeto @Evie-Skinner18 @belev @beven @FatimaMubeen @lifeLessCoder

**Comment by amulya349** [comment]
I have created a PR with fibonacci_search implementation in python.
