### ISSUE TITLE
Add sorting algorithms

### ISSUE THREAD

**Issue by kvaluruk** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#487]
**Contributing Guidelines**
- The repository is structured language-wise i.e. algorithms in a certain language go in a specific folder.
- The naming convention to be followed is `algo_name.language_extention` i.e. the overall path should be `language/algo_name.language_extention`
- It is your choice to include only the function or the entire program for the algorithm.
- If the folder for your language does not exist, create a new one.
- Don't be afraid to make a PR!

**How to make PR**
1. Fork Repo on Web Page
2. Make your changes on your forked repo
3. Make Pull Request to master

**Comment by luisejrobles** [comment]
I'm going to add a few 👍

**Comment by pm451** [comment]
I'm going to make a bubble sort for C.

**Comment by pm451** [comment]
> 
> 
> I'm going to make a bubble sort for C.

[https://github.com/pm451/Data-Structures-And-Algorithms-Hacktoberfest18/blob/master/c/algorithm/BubbleSort.c](url)

**Comment by ananthuc73** [comment]
Will add heap sort in c

**Comment by ananthuc73** [comment]
Another pull request to add insertion sort in c#

**Comment by Rahul255** [comment]
add heap sort in c

**Comment by amohata007** [comment]
https://github.com/amohata007/Hacktoberfest
contribute here....it is totally awesome and very easy to contribute.
@kvaluruk @luisejrobles @pm451 @ananthuc73 @Rahul255 @A-Alaa @abc-xx @abhaygupta97 @abhishall @wikiabhi @swastikbanerjee07 @NicolaPasquali @dadobt @danmcatee

**Comment by athulyaraj** [comment]
Added pigeonhole sort implementation in java
https://github.com/kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18/pull/713

**Comment by phenomenal45** [comment]
sir, I want to contribute to this project.

**Comment by Lightning101** [comment]
i would like to contribute this project will try to use a language less commonly used

**Comment by Malvikabhalla99** [comment]
i would like to contribute to it
